### ISSUE TITLE
ZcashTransaction.Overview.value including the fee

### ISSUE THREAD

**Issue by tw0po1nt** [zcash/ZcashLightClientKit#1292]
### Describe the issue
Please provide a general summary of the issue you're experiencing
`ZcashTransaction.Overview` objects returned by `SDKSynchronizer.allTransactions()` are populating the `value` field with `zec amount + fee`, instead of just `zecAmount`. I expect `value` to be a subtotal such that I can show line items for subtotal, fee, and total. This field containing the fee is confusing.

#### If so, please list the steps to reproduce below:
1. Launch [Nighthawk 2.0 ](https://github.com/nighthawk-apps/nighthawk-ios-wallet)
2. Sync a wallet with funds or create a new wallet and send some funds to it 
3. Send funds to a different wallet
4. On success, observe the list item row for the transaction on the home screen, then navigate to the transaction details listing for the sent transaction.

### Expected behaviour
Tell us what should happen

The amount shown in the listing should be the amount the recipient will receive + fees paid by the sender. In transaction details, the subtotal field should show the amount the recipient will receive, the fee line should show fees paid by sender, and the total line should show amount recipient will receive + fees paid by sender.

### Actual behaviour + errors
Tell us what happens instead including any noticeable error output (any messages
displayed on-screen when e.g. a crash occurred)

The total amounts shown in both places are showing with doubled fee amount. The subtotal line is showing as amount recipient will receive + fees.

Debugger screenshot:
![Screenshot 2023-09-27 at 8 17 40 AM](https://github.com/zcash/ZcashLightClientKit/assets/66689851/44b5355d-9df4-441a-b878-e3d922c999de)

Txn details of sender - summary:
![Simulator Screenshot - iPhone SE (3rd generation) - 2023-09-27 at 08 18 11](https://github.com/zcash/ZcashLightClientKit/assets/66689851/c28fcbe5-64c6-460a-9ad7-6dc20553300a)

Txn details of sender - line items:
![Simulator Screenshot - iPhone SE (3rd generation) - 2023-09-27 at 08 18 30](https://github.com/zcash/ZcashLightClientKit/assets/66689851/153e4000-931b-4c74-ac6d-135e92cd4727)

Txn details of recipient:
![Simulator Screenshot - iPhone 15 Pro Max - 2023-09-27 at 08 28 47](https://github.com/zcash/ZcashLightClientKit/assets/66689851/ba764625-8722-4889-983b-906adb25ce09)

- App Version: 2.0 build 4
- iOS Version: 17.0
- Device: (if applies) N/A

**Comment by tw0po1nt** [comment]
I have confirmed that this is happening for shielded and transparent transactions alike.

**Comment by nuttycom** [comment]
So, there's a bit of complexity here, and I'd like your input on what we should do about it.

For reference, these are the views that are used to populate the transaction overview and transaction detail, respectively: https://github.com/zcash/librustzcash/blob/main/zcash_client_sqlite/src/wallet/init.rs#L435-L542 and  https://github.com/zcash/librustzcash/blob/main/zcash_client_sqlite/src/wallet/init.rs#L544-L587

In general, we have to consider the full range of operations available to the protocol when reporting transaction history, because users may have imported seeds from other wallets that provide functionality for creating transactions that does not exist in the wallet SDK. In all cases, wallet balance is defined as the sum of unspent outputs; transaction balance is substantially trickier because the following may be true:
* Not all of the inputs to the transaction may have belonged to the wallet; some could have belonged to other wallets.
* It's possible to have both normal outputs back to the originating wallet and change outputs.

Furthermore, we cannot reliably determine transaction fees when performing recovery, because to do so at present requires fetching the transparent prevouts spent in the transaction, which we don't have the ability to do from within the Rust backend. Full nodes don't have this problem because they have the full output set, but light wallets don't maintain this (and this is part of the reason that v6 transactions will have explicit fee amounts and be required to balance by consensus.)

As such, in the transaction overview, what is reported as the value is the _net value delta to the wallet_ caused by the transaction. The fee amount, if known, is reported separately; that fee amount might be considered paid by the transaction inputs that were owned by this wallet, or by the transaction inputs owned by another wallet; in the general case, the fee is paid from the pool of input funds. If all of those input funds belonged to this wallet, that's great, but we don't want the meaning of the value of the transaction (as the net delta for this wallet) to vary across transactions depending upon the source of funds.

Another important thing to note is that the value of transparent UTXOs that belong to the wallet that were spent in the transaction may be entirely unknown. The UTXOs known to the wallet are only those that exist in the UTXO set at the chain tip as of the recovery height and later; previously spent UTXOs belonging to the wallet will never be provided by the light wallet server, because those have fallen out of the UTXO set. 

In summary, we can provide the following:
* net value delta to the wallet
* fee information, but only for transactions created by the wallet and only for transactions created after the chain tip at the time that the wallet was initialized (transactions created after the recover-until height)
* information about the outputs created by the transaction that are either owned by the wallet (unspent transparent UTXOs, change amounts, and outputs that are decryptable by the the wallet's OVK).

We cannot reliably provide:
* Fee amount (prior to V6 transactions)
* Comprehensive information about inputs to the transaction (there may be inputs from other parties and/or transparent inputs that we can't see)
* Comprehensive information about outputs from the transaction (there may be outputs generated using a random OVK, already spent transparent outputs belonging to the wallet may or may not be visible depending upon whether those outputs were created after the recover-until height, and other transparent outputs to third parties will only be known after transaction enhancement.)

**Comment by nuttycom** [comment]
All of this is a bit of a long-winded way to say that the "subtotal" concept you have in this UI is not well-defined. You should instead report the net value delta, and then provide information about things like the fee as additional detail.

**Comment by nuttycom** [comment]
@tw0po1nt given the above, is there a specific change that we should make, or can this be closed?

**Comment by tw0po1nt** [comment]
@nuttycom Thanks for the explanation. We have opted to show net value delta and remove the concept of subtotal entirely, as you suggested. This issue can be closed.
