### ISSUE TITLE
Placeholder: iOS output and spend parameters management

### ISSUE THREAD

**Issue by braddmiller** [zcash/ZcashLightClientKit#22]
add details on download and managment

**Comment by gmale** [comment]
Sapling spend and output params are not needed until the user attempts to spend funds, which usually is not for a long while after first install.

The current Android implementation delays the download of these files until the moment when a transaction is being submitted to the network. The tradeoff is the first transaction takes about 2 seconds longer than others. However, the apps have the freedom to load these files at any point before then (even as a background task). As long as they exist at the moment a send happens, then everything works. [If they don't exist, they're loaded](https://github.com/zcash/zcash-android-wallet-sdk/blob/79184c3cdd23087ed1835ced46df500834a56a84/src/main/java/cash/z/ecc/android/sdk/transaction/WalletTransactionEncoder.kt#L109).

Also, these params are kept in the app cache directory so that when the user clears cache on Android (not sure if iOS has an equivalent) then they can free up 50MB of space and the app just reloads these parameter files the next time they are required.

A "good enough" implementation here should be low hanging fruit, since a simple RESTful request can be made at the right time to load and store the files if and only if they're missing.

**Comment by pacu** [comment]
Ideally this should be handled as a deferred download or happen explicitly. It's possible to in android to request a background download for the system to allocate in a better time.
