### ISSUE TITLE
Make rewind and re-sync API public

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#245]
Let wallet developers have to option to rewind to a certain height and re-sync with the blockchain.

**Rationale**:
the Zcash SDK depends on lightclient protocol which holds a lot of state, when that state suddenly presents errors, there are not much troubleshooting steps to do than re-syncing the wallet from its birthday. That requires users to backup their seed if they haven't already, or repeat themselves if they don't have the backup at their disposal. 

Providing developers the ability to rewind the synchronizer height to an arbitrary height of their choosing could open a way of less cumbersome troubleshooting and a path to error recovery attempts that are invisible to the user or available at a single tap.

**Criteria**:

There's a public API on the Synchronizer that rewinds the current state to a given blockheight.
The given blockheight should be greater or equal than the provided birthday.

Synchronizer must be able to resume syncing just by calling start() again.

**Out of scope:**
 Rewinding past birthday implies more work, because the Iniitalizer should be able to nuke the databases, preserving credentials and saving a new birthday, then to initialize the whole stack again. 

**Tests:**

testSimpleRewind:
sync wallet and check exisiting balances.
rewind to height H where H > birthday
resume syncronizer

result: chaintip is reached and balances are correct according to previous values.

testForwardHeight:
reach chaintip with synchronizer
attempt to call rewind to height H where H > ChainTip

result: API call should fail with an exception validating the height

testRewindPastBirthday:
reach chaintip with synchronizer
attempt to call rewind to height H where H < WalletBirthday

result: API call should fail with an exception validating the height provided.

**Comment by gmale** [comment]
looks good. 

I'm not sure this is a strict requirement:
> Synchronizer must be able to resume syncing just by calling start() again.

On Android, as currently designed, the synchronizer can only be started once. I think maybe the true requirement here is that rewind not conflict with sync.

Another thing to consider is that we currently poll on 20 second boundaries in order to prevent timing attacks. If we give too much control here, it could result in blocks being fetched in the gaps. Maybe that's okay (we should check w/ @defuse) or maybe it would be better to queue the rewind request so that it only happens on a 20s boundary.

This could be accomplished by rewinding all the local data and then letting the next compactblock fetch happen organically, when it is normally scheduled. This would have the side benefit of not clashing with sync, automatically.

**Comment by pacu** [comment]
Probably we need then a more thorough refactor on the Synchronizers behavior. 

In iOS you need to be able to start and stop the thing because of App lifecycle and OS policies. Also, iOS SDK must support imperative and reactive programming paradigms. So we can't impose a cadence to developers that easily. 

We should though, improve polling interval cadence which, currently is not a core part of the syncing process but an addition from a PR  instead. We can refactor the SDK synchronizer to ma

**Comment by defuse** [comment]
Sorry for the super late reply. Since this should be a rare occurrence and there are already worse privacy problems in the protocol I wouldn't worry about timing this kind of thing regularly.

However more broadly I think it's better to unit- and integration-test the hell out of the syncing protocol so that rescanning is never needed!
