### ISSUE TITLE
Create Rust-less build for SDK

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#328]
Based on the research done on #311 we want to apply the rustless build approach

Requirements:
- [x] Repository for the ZcashRustLib or MonoRepo inside the ZcashLightClientKit repo  (@pacu and @dh-ecc)
- [x] ZcashLightClientKit can be distributed over Cocoapods and Swift Package Manager

notes: 
- for rust builds use the cargo.toml on 0.12.0-beta.5

**Comment by geffenz** [comment]
Information from duplicate ticket : 
What is your feature request?
Currently, building the SDK requires a native Rust build as well. This request is to consider decoupling building the Rust layer from building the SDK layer. The idea would be to have two libraries:

sdk-native-lib which compiles the rust layer and emits an artifact
sdk-lib consumes sdk-native-lib
sdk-native-lib can be published and versioned separately from sdk-lib.

How would this feature help you?
This would significantly simplify and speed up builds of the sdk-lib.

To keep the ability to modify both the sdk-native-lib and sdk-lib at the same time, we can configure a build flag to toggle between the modes of consuming the sdk-native-lib gradle module versus consuming the sdk-native-lib maven artifact

**Comment by swansontec** [comment]
Another benefit of the XCFramework approach is that it will finally allow the M1 macs to run this library in the simulator, without Rosetta. This is because an XCFramework allows arm64 iphoneos and arm64 iphonesimulator builds to exist side-by-side, whereas the current `vendored_libraries` approach does not.

Another problem with the current approach, that this new approach should fix, is that switching back & forth between the x86 simulator and arm64 physical phone requires an `rm -rf Pods ; pod install` to force-build the static library. Again, the fact that an XCFramework allows multiple builds to exist side-by-side means this should no longer be a problem.

**Comment by dh-ecc** [comment]
@pacu @geffenz I think this is good to close now with #338 being merged and https://github.com/zcash-hackworks/zcash-light-client-ffi/pull/1. I've also added a small PR with a Readme so you don't have to guess how to do things 😅. https://github.com/zcash-hackworks/zcash-light-client-ffi/issues/2
