### ISSUE TITLE
Non-Sendable UserDefaults warnings

### ISSUE THREAD

**Issue by LukasKorba** [zcash/ZcashLightClientKit#538]
UserDefaults dependency has been refactored to async but UserDefaults is non-sendable and we have warnings in WrappedUserDefaults swift file. Those warning will eventually become error when Swift 6 is released so we need to fix it.

**Comment by Chlup** [comment]
This can be solved by one line:
`extension UserDefaults: @unchecked Sendable { }`

Now the question is if this is the right fix for this situation. I think it should be. `UserDefaults` are thread-safe. It's explicitly said in the documentation. So I think that `UserDefaults` should be marked as `Sendable` in Foundation. But it is not for some reason. 

If this is not ok solution then we probably have to add some wrapper which will be `Sendable` and will use `UserDefaults` inside. If we don't trust documentation about `UserDefaults`'s thread-safety we can add some own locking. But I don't think it's worth it because effectively it will be the same as line above.

And second question is if this should be in SDK. Swift doesn't allow to use access modifiers when using extension which adds protocol conformances. So even if we add this line to SDK then app code won't see this extension. Or Am I wrong? 

@pacu @LukasKorba Can you give me your opinion please?

**Comment by LukasKorba** [comment]
> This can be solved by one line: `extension UserDefaults: @unchecked Sendable { }`
> 
> Now the question is if this is the right fix for this situation. 
> @pacu @LukasKorba Can you give me your opinion please?

We can actually do something else and don't loose the thread safety, suggestion:

```swift
static func live(
        userDefaults: @autoclosure @escaping () -> UserDefaults = .standard
    ) -> Self {
        Self(
            objectForKey: { userDefaults().object(forKey: $0) },
            remove: { userDefaults().removeObject(forKey: $0) },
            setValue: { userDefaults().set($0, forKey: $1) },
            synchronize: { userDefaults().synchronize() }
        )
    }
```

**Comment by Chlup** [comment]
This issue should be opened in Secant repo. Not in SDK repo. I did so - https://github.com/zcash/secant-ios-wallet/issues/420.
