### ISSUE TITLE
Switch from event based notifications to state based notifications

### ISSUE THREAD

**Issue by Chlup** [zcash/ZcashLightClientKit#724]
Currently the SDK is using event based notifications API. It should be investigated what it means to switch to state based notifications. Draft of the new API must be made first.

**Comment by Chlup** [comment]
I will write this from perspective of iOS. I guess current state of the Android is very similar. Final solution should apply to both platforms.

**Current SDK (`SDKSynchronizer` class) API:**

- Notifications:
   - SDKSyncronizerStarted 
   - SDKSyncronizerProgressUpdated
   - SDKSynchronizerStatusWillUpdate
   - SDKSyncronizerSynced
   - SDKSyncronizerStopped
   - SDKSyncronizerDisconnected
   - SDKSynchronizerSyncing
   - SDKSyncronizerEnhancing
   - SDKSyncronizerFetching
   - synchronizerMinedTransaction
   - synchronizerFoundTransactions
   - SDKSynchronizerFailed
   - SynchronizerConnectionStateChanged

- `SDKSynchronizer` has `var status: SyncStatus`. When status is updated then `synchronizerStatusWillUpdate` notification is sent. `SyncStatus` is enum which has these symbols:
   ```
   public enum SyncStatus: Equatable {
    /// Indicates that this Synchronizer is actively preparing to start,
    /// which usually involves setting up database tables, migrations or
    /// taking other maintenance steps that need to occur after an upgrade.
    case unprepared

    /// Downloading and scanning blocks.
    case syncing(_ progress: BlockProgress)

    /// Indicates that this Synchronizer is actively enhancing newly scanned blocks
    /// with additional transaction details, fetched from the server.
    case enhancing(_ progress: EnhancementProgress)

    /// fetches the transparent balance and stores it locally
    case fetching

    /// Indicates that this Synchronizer is fully up to date and ready for all wallet functions.
    /// When set, a UI element may want to turn green.
    case synced

    /// Indicates that [stop] has been called on this Synchronizer and it will no longer be used.
    case stopped

    /// Indicates that this Synchronizer is disconnected from its lightwalletd server.
    /// When set, a UI element may want to turn red.
    case disconnected

    case error(_ error: Error)
    ```
- `SDKSychronizer` has publisher (reactive stream) that reports state. State is this structure:
    ```
    public struct SynchronizerState: Equatable {
        public var shieldedBalance: WalletBalance
        public var transparentBalance: WalletBalance
        public var syncStatus: SyncStatus
        public var latestScannedHeight: BlockHeight
    }
    ```
- `SDKSynchronizer` has `progress` property which tracks progress of sync process. When `progress` is updated then `SDKSyncronizerProgressUpdated` notification is sent.

**These are all the main APIs of the SDK (`SDKSynchronizer` class) that are used to report what is going on. In general what should be done?**
- Unify technology that is used to report from the SDK. Currently mix of Combine and Notifications is used. 
- Make it easy to control how many progress updates app receives while it doesn't have to be afraid of miss some status/state update.
- Make the SDK API more clear and easier to use.


**Here is my draft of the solution:**
```
public struct NewSynchronizerAPIDraft {
    public enum Status {
        case unprepared
        case syncing
        case enhancing
        case fetching
        case synced
        case stopped
        case disconnected
        case error(_ error: Error)
    }

    public enum Event {
        case minedTransaction
        case foundTransactions
        case connectivityStateChanged
    }

    public let statusStream: AnyPublisher<Status, Never> //reactive stream, CurrentValueSubject
    public let progressStream: AnyPublisher<Float, Never> //reactive stream, CurrentValueSubject
    public let eventsStream: AnyPublisher<Event, Never> //reactive stream, PassthroughSubject
}
```

- Only `Combine` (reactive streams) is used to report what is going on. All the notifications are gone. On Android side `Combine` can be replaced with similar technology. Or any other technology that fits this case.
- `statusStream` is reactive stream that reports `Status`. `Status` describes in which phase of the sync process the SDK is. It's almost the same as current `SyncStatus`. It just doesn't contain `progress` anymore. Thanks to that amount of status updates will be low and it's easy to handle.
- `progressStream` is reactive stream that reports only progress. Progress is updated very often. If amount of updates should be handled on the SDK side it should be easy because progress is just number. If the amount of received updates should be handled on app side it should be easy because progress is just number. 
- **Unresolved question**: Should be progress global from `unprepared` (0%) to `synced` (100%)? Or it should be local? By local I mean for `syncing` the SDK would report progress from 0% to 100%. And for `enhancing` the SDK would report progress from 0% to 100%. And the same for `fetching`.
- Application can easily merge signals from `statusStream` and `progressStream` and handle them together. And then app just have to render UI for the given state and that's it. This can be achieved when using combine. I am not sure how it can be done on Android.
- `eventsStream` is reactive stream. It replaces these notifications for now: `synchronizerMinedTransaction`, `synchronizerFoundTransactions`, `SynchronizerConnectionStateChanged`. Instead of these notifications event is sent through the stream. We can keep it simple and we don't need to send any data through this stream. App can simply subscribe to this stream and then use SDK API according to received event.

**Comment by ccjernigan** [comment]
Moving away from notifications sound like a nice improvement.  I had a few minor comments.  These may not all apply to iOS.  I'm just leveraging my knowledge of how the Android SDK works currently and where I think we want it to go.  
 - Instead of `unprepared`, what about `initializing`?  Unprepared sounds like a client needs to do something, while initializing sounds like the client just need to wait a bit
 - Instead of erasing to AnyPublisher, would there be any value to creating some kind of wrapper to provide a read-only CurrentValueSubject?  We use StateFlow in Kotlin which provides a stream where clients can also just read the current value if needed.
 - I don't think we have a great way to predict how long each stage will take, so how would we generate a global progress percentage?
 - I think we will benefit from a special sync status of `Refreshing` which is separate from `Syncing`.  Syncing means the app is many blocks behind, while Refreshing means the app is maybe 2-3 blocks or less behind.  Refreshing is what the app does every 45 seconds or so.  Currently this causes our UI to flicker, which we probably would like to solve.  An alternative would be something on the Syncing state to indicate how far behind it is so that the UI can debounce.
 - How is disconnected different from an error?  Could disconnected just be one of the errors that we report instead?
 - Do we need a stopped state?

**Comment by Chlup** [comment]
> Moving away from notifications sound like a nice improvement. I had a few minor comments. These may not all apply to iOS. I'm just leveraging my knowledge of how the Android SDK works currently and where I think we want it to go.
> 
> * Instead of `unprepared`, what about `initializing`?  Unprepared sounds like a client needs to do something, while initializing sounds like the client just need to wait a bit
In unprepared state on iOS a client must do something. Client must call `SDKSynchronizer.prepare()` and pass seed to this call. Otherwise sync won't be possible. Maybe we could add one more state between `unprepared` and `syncing`. Something like `ready` or `idle` to signalise that SDK is prepared and ready to be synced.

> * Instead of erasing to AnyPublisher, would there be any value to creating some kind of wrapper to provide a read-only CurrentValueSubject?  We use StateFlow in Kotlin which provides a stream where clients can also just read the current value if needed.
`AnyPublisher` in `Combine` is read-only. `CurrentValueSubject` in comment just marks type of subject that is backing the stream and which defines behavior of the stream.

> * I don't think we have a great way to predict how long each stage will take, so how would we generate a global progress percentage?
The the answer to my question is that progress will be local for each state then.

> * I think we will benefit from a special sync status of `Refreshing` which is separate from `Syncing`.  Syncing means the app is many blocks behind, while Refreshing means the app is maybe 2-3 blocks or less behind.  Refreshing is what the app does every 45 seconds or so.  Currently this causes our UI to flicker, which we probably would like to solve.  An alternative would be something on the Syncing state to indicate how far behind it is so that the UI can debounce.
On iOS we don't recognise this at this moment. But I think we could if we want to. Or we could have in state something like `syncing(amountOfBlocksToSync: Int)`. 
@pacu What do you think?

> * How is disconnected different from an error?  Could disconnected just be one of the errors that we report instead?
I think that SDK switches to `disconnected` state when it thinks that network connection is lost. Maybe we could really merge disconnected state to error state with specific error.
@pacu What do you think about this? What is motivation behind `disconnected` state?

> * Do we need a stopped state?
That is good question. On iOS the SDK switch to stopped state when somebody calls explicitly `stop()`. Maybe if we introduce that state between `unprepared` and `syncing` (which I mention above) we could switch to that state.
@pacu What do you think about this?

**Comment by pacu** [comment]
I think there are a couple of things.

First, balance has been left aside of the discussion. It must be obtained reactively to avoid `database is locked` errors from the rust backend. This is a common issue when querying the balance while rust is accessing the dataDb for any reason (scanning, decrypting, validating).

Balance should be cached and be shown optimistically throughout the progress of the sync process.

currently iOS is scanning 100 blocks at once so it can query a new balance every 100 blocks. It can actually do that in parallel while downloading if needed to avoid introducing more overhead. 

Showing balance is the main reason I implemented SynchronizerState. it's mostly info that can't be queried at will because of the current architecture.

```
public struct SynchronizerState: Equatable {
    public var shieldedBalance: WalletBalance
    public var transparentBalance: WalletBalance
    public var syncStatus: SyncStatus
    public var latestScannedHeight: BlockHeight
}
```

> Instead of unprepared, what about initializing? Unprepared sounds like a client needs to do something, while initializing sounds like the client just need to wait a bit

I wouldn't call it a gerund because it's not doing anything, just waiting for the prepare() call from the SDK client.

> Instead of erasing to AnyPublisher, would there be any value to creating some kind of wrapper to provide a read-only CurrentValueSubject? We use StateFlow in Kotlin which provides a stream where clients can also just read the current value if needed.

I agree. I like CurrentValueSubjects better. Wallet developers wanting to use AnyPublisher can always erase at will. It is true that CurrentValueSubject is not read-only, [but it can easily be turned into that](https://stackoverflow.com/questions/69582148/read-only-currentvaluesubject).

> I think we will benefit from a special sync status of Refreshing which is separate from Syncing. Syncing means the app is many blocks behind, while Refreshing means the app is maybe 2-3 blocks or less behind. Refreshing is what the app does every 45 seconds or so. Currently this causes our UI to flicker, which we probably would like to solve. An alternative would be something on the Syncing state to indicate how far behind it is so that the UI can debounce.

I think this is a good idea. One caveat is that if we can't avoid the sandblasting effect, 5 blocks would mean 2 minutes worth of processing. 

> How is disconnected different from an error? Could disconnected just be one of the errors that we report instead? 
it's a different sort of error. Since we don't have a layered Error API, the easiest is to detach disconnection from the error state. 

> Do we need a stopped state?

how would you handle scenarios where the synchronizer is doing nothing becase the wallet application wants it to?

I think there are many situations that we are not handling that could use the stopped state. Like the user not wanting the app to update (because is on data plan or the network is not trusted) but still wants to browse the wallet's local history. Or plane mode. Which is deliberate state where the user knows that no internet connection might be available and shouldn't be treated as an error because it is the user instructing that it should be like that.

> On iOS the SDK switch to stopped state when somebody calls explicitly stop(). Maybe if we introduce that state between unprepared and syncing (which I mention above) we could switch to that state.
@pacu What do you think about this?

Long time ago, we used to have a user story about "disconnected states" which is the whereabouts of the synchronizer from the POV of connectivity. We could get rid of the `unprepared` state if so, but that can happen once we have a more comprehensive and layered Error API. Now we have a scenario that needs handling, which is the two-step initialization that generated the `unprepared` state and also the fact that we probably need some state that indicates a "parking" break for the SDK as well

**Comment by Chlup** [comment]
> I think there are a couple of things.
> 
> First, balance has been left aside of the discussion. It must be obtained reactively to avoid `database is locked` errors from the rust backend. This is a common issue when querying the balance while rust is accessing the dataDb for any reason (scanning, decrypting, validating).
> 
> Balance should be cached and be shown optimistically throughout the progress of the sync process.
> 
> currently iOS is scanning 100 blocks at once so it can query a new balance every 100 blocks. It can actually do that in parallel while downloading if needed to avoid introducing more overhead.
> 
> Showing balance is the main reason I implemented SynchronizerState. it's mostly info that can't be queried at will because of the current architecture.
> 
> ```
> public struct SynchronizerState: Equatable {
>     public var shieldedBalance: WalletBalance
>     public var transparentBalance: WalletBalance
>     public var syncStatus: SyncStatus
>     public var latestScannedHeight: BlockHeight
> }
> ```

My idea was that when new balance is available specific signal is sent via `eventsStream` and then app can read right property to get latest balance.

> 
>  > Instead of unprepared, what about initializing? Unprepared sounds like a client needs to do something, while initializing sounds like the client just need to wait a bit
> 
> I wouldn't call it a gerund because it's not doing anything, just waiting for the prepare() call from the SDK client.

What do you mean by "gerund" please?

> 
> > Instead of erasing to AnyPublisher, would there be any value to creating some kind of wrapper to provide a read-only CurrentValueSubject? We use StateFlow in Kotlin which provides a stream where clients can also just read the current value if needed.
> 
> I agree. I like CurrentValueSubjects better. Wallet developers wanting to use AnyPublisher can always erase at will. It is true that CurrentValueSubject is not read-only, [but it can easily be turned into that](https://stackoverflow.com/questions/69582148/read-only-currentvaluesubject).

We can call it however we want. I just think that we shouldn't provide any writable object. But we are in sync here. In previous job we had aliases: `BehaviorObservable`, `PublisherObservable` to have read only object with type which tells you behavior right away.

**Comment by pacu** [comment]
>What do you mean by "gerund" please?
I mean that the state shouldn't be a word denoting a something that in ongoing like sync-ing or initializ-ing because it's a stale state waiting for an action. In this case the unprepared state tells you that the SDK needs something to be able to start which is the `prepare()` call.
